name: Run tests and build artifacts

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  tests-and-build-artifacts:

    strategy:
      matrix:
        go-version: [1.15.7]
        os: [ubuntu, macos, windows]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -v ./...

    - name: Build binary
      run: go build -v

    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: lirisi-${{ matrix.os }}
        path: lirisi*
